# Copyright 2023-2025 Amazon.com, Inc. or its affiliates.

name: osml_tile_server
channels:
  - conda-forge
dependencies:
  - conda-forge::cryptography=42.0.2
  - conda-forge::gdal=3.12.0
  - conda-forge::proj=9.7.0
  - conda-forge::numpy==2.3.4
