# Copyright 2024-2025 Amazon.com, Inc. or its affiliates.
name: tile_server_test
channels:
  - conda-forge
dependencies:
  - python=3.13
  - python-json-logger
  - requests
  - locust
  - boto3
  - awslambdaric
