name: Validate

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

env:
  AWS_REGION: "us-west-2"
  AWS_PAGER: ""

permissions:
  id-token: write
  contents: read
  actions: read

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    uses: ./.github/workflows/check-pending-workflow.yml
    secrets: inherit

  get-aws-region:
    runs-on: ubuntu-latest
    outputs:
      aws_region: ${{ env.AWS_REGION }}
    steps:
      - name: Set AWS Region
        run: |
          echo "Using AWS Region: ${{ env.AWS_REGION }}"

  deploy:
    needs:
      - check
      - get-aws-region
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: ${{ needs.get-aws-region.outputs.aws_region }}
      build_from_source: true
    secrets: inherit

  test:
    needs:
      - deploy
      - get-aws-region
    uses: ./.github/workflows/run-integration-tests.yml
    with:
      aws_region: ${{ needs.get-aws-region.outputs.aws_region }}
    secrets: inherit

  destroy:
    if: always()
    needs:
      - check
      - deploy
      - test
      - get-aws-region
    uses: ./.github/workflows/destroy.yml
    with:
      aws_region: ${{ needs.get-aws-region.outputs.aws_region }}
    secrets: inherit
