name: Deploy Infrastructure

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      build_from_source:
        required: false
        type: boolean
        default: true
    secrets:
      TILE_SERVER_ACCOUNT_ID:
        required: true

env:
  AWS_REGION: ${{ inputs.aws_region }}
  AWS_PAGER: ""
  NODE_VERSION: '24'
  PYTHON_VERSION: '3.13'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Setup AWS OIDC
        uses: ./.github/actions/setup-aws-oidc
        with:
          aws_region: ${{ inputs.aws_region }}
          account_id: ${{ secrets.TILE_SERVER_ACCOUNT_ID }}
          role_duration_seconds: '7200'
      - name: Setup CDK
        uses: ./.github/actions/setup-cdk
        with:
          node_version: ${{ env.NODE_VERSION }}
      - name: Generate deployment.json
        uses: ./.github/actions/generate-deployment-json
        with:
          account_id: ${{ secrets.TILE_SERVER_ACCOUNT_ID }}
          build_from_source: ${{ inputs.build_from_source }}
      - name: Build and synthesize CDK
        working-directory: cdk
        run: |
          cdk synth
      - name: Bootstrap CDK
        working-directory: cdk
        run: cdk bootstrap --force
      - name: Deploy CDK infrastructure
        working-directory: cdk
        run: cdk deploy --all --require-approval never --concurrency 3
