name: release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tox:
    uses: ./.github/workflows/tox.yml
    secrets: inherit
  pypi:
    needs: [tox]
    uses: ./.github/workflows/pypi.yml
    secrets: inherit
  docker:
    needs: [tox]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
