name: Notify Slack

on:
  pull_request:
    types: [opened]
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

jobs:
  notify-pr-created:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Send PR Created Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: '${{github.event.repository.name}} PR Created: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}'
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
          SLACK_MESSAGE: 'PR Created ${{ github.event.pull_request.html_url }}'
